spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/users_db?useSSL=false
        username: root
    jpa:
       hibernate.ddl-auto: update
       generate-ddl: true
       show-sql: true
